from typing import Protocol


class DatasetStore(Protocol):
    def publish(self, dataset_id: str, files: dict[str, bytes], metadata: dict) -> dict: ...
    def verify(self, dataset_id: str) -> dict: ...


class ArtifactStore(Protocol):
    def publish(self, artifact_id: str, files: dict[str, bytes], metadata: dict) -> dict: ...
    def verify(self, artifact_id: str) -> dict: ...


class RunStore(Protocol):
    def create(self, run_id: str, specification: dict) -> dict: ...
    def read(self, run_id: str) -> dict: ...
    def transition(self, run_id: str, expected: str, following: str) -> dict: ...
