import argparse


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(prog="toy-tune", description="Portable experiment bootstrap (CPU foundation).")
    commands = root.add_subparsers(dest="command", required=True)
    doctor = commands.add_parser("doctor", help="Inspect current machine without importing accelerator libraries.")
    doctor.add_argument("--runtime", required=True)
    doctor.add_argument("--workspace")
    doctor.add_argument("--probe-gpu", action="store_true")
    prepare = commands.add_parser("prepare", help="Validate and publish a frozen source bundle as a dataset.")
    prepare.add_argument("--runtime", required=True)
    prepare.add_argument("--workspace")
    source = prepare.add_mutually_exclusive_group(required=True)
    source.add_argument("--source", help="legacy explicit JSON source bundle")
    source.add_argument("--frozen-packet", help="DB-derived reviewed style packet")
    prepare.add_argument("--split", help="required with --source; frozen packets carry their split")
    prepare.add_argument("--allow-context-overlap", action="store_true")
    verify = commands.add_parser("verify-dataset", help="Verify all payload checksums of a published dataset.")
    verify.add_argument("--runtime", required=True)
    verify.add_argument("--workspace")
    verify.add_argument("--dataset-id", required=True)
    train = commands.add_parser("train-lora", help="Run a bounded Gemma 4 E2B LoRA trial on pinned CUDA data.")
    train.add_argument("--runtime", required=True)
    train.add_argument("--workspace")
    train.add_argument("--dataset-id", required=True)
    train.add_argument("--request", required=True)
    train.add_argument("--output-dir", required=True)
    train.add_argument("--sample-id", action="append", required=True,
                       help="reviewed train sample ID; repeat for 1–4 explicitly chosen examples")
    train.add_argument("--max-steps", type=int, default=2)
    train.add_argument("--max-tokens", type=int, default=2048)
    reload = commands.add_parser("verify-lora", help="Reload one trained adapter in a fresh process.")
    reload.add_argument("--runtime", required=True)
    reload.add_argument("--workspace")
    reload.add_argument("--output-dir", required=True)
    return root
